// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyAUub_Ml-JhmdmmjVBOdEwECaGszNWU1FA",
  authDomain: "oincrivelprojetodapaeladaapi.firebaseapp.com",
  projectId: "oincrivelprojetodapaeladaapi",
  storageBucket: "oincrivelprojetodapaeladaapi.firebasestorage.app",
  messagingSenderId: "812274976282",
  appId: "1:812274976282:web:a40ce7ee47fe9b433873a3"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);